ALTER TABLE ai_logs ADD COLUMN user_id INT NULL;
ALTER TABLE ai_logs ADD COLUMN origin VARCHAR(120) NULL;
ALTER TABLE ai_logs ADD COLUMN function_name VARCHAR(120) NULL;
ALTER TABLE ai_logs ADD COLUMN provider VARCHAR(60) NULL;
ALTER TABLE ai_logs ADD COLUMN model VARCHAR(120) NULL;
ALTER TABLE ai_logs ADD COLUMN duration_ms INT NULL;
ALTER TABLE ai_logs ADD COLUMN tokens_estimated INT NULL;
ALTER TABLE ai_logs ADD COLUMN cost_estimated DECIMAL(12,6) NULL;
