"""auto update

Revision ID: 486d476a11a2
Revises: 562039a7015a
Create Date: 2026-07-02 23:11:28.153905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486d476a11a2'
down_revision: Union[str, Sequence[str], None] = '562039a7015a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('processed_url', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), server_default='image', nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_selected', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_media_id'), 'offer_media', ['id'], unique=False)
    op.create_table('whatsapp_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('instance', sa.String(), nullable=True),
    sa.Column('sender_phone', sa.String(), nullable=True),
    sa.Column('raw_data', sa.String(), nullable=True),
    sa.Column('processed', sa.String(), server_default='pending', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_events_id'), 'whatsapp_events', ['id'], unique=False)
    op.add_column('buyers', sa.Column('email', sa.String(), nullable=True))
    op.add_column('buyers', sa.Column('company', sa.String(), nullable=True))
    op.add_column('buyers', sa.Column('city', sa.String(), nullable=True))
    op.add_column('buyers', sa.Column('observations', sa.String(), nullable=True))
    op.alter_column('buyers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('buyers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('offers', sa.Column('version', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('supplier_price', sa.Float(), nullable=True))
    op.add_column('offers', sa.Column('transmission', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('suggested_category', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('is_auction', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('offers', sa.Column('sold_buyer_id', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('sale_notes', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('vehicle_dossier_id', sa.Integer(), nullable=True))
    op.alter_column('offers', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('suppliers', sa.Column('category', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('city', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('observations', sa.String(), nullable=True))
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('suppliers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('suppliers', 'observations')
    op.drop_column('suppliers', 'city')
    op.drop_column('suppliers', 'category')
    op.alter_column('offers', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('offers', 'vehicle_dossier_id')
    op.drop_column('offers', 'sale_notes')
    op.drop_column('offers', 'sold_buyer_id')
    op.drop_column('offers', 'is_auction')
    op.drop_column('offers', 'suggested_category')
    op.drop_column('offers', 'transmission')
    op.drop_column('offers', 'supplier_price')
    op.drop_column('offers', 'version')
    op.alter_column('buyers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('buyers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('buyers', 'observations')
    op.drop_column('buyers', 'city')
    op.drop_column('buyers', 'company')
    op.drop_column('buyers', 'email')
    op.drop_index(op.f('ix_whatsapp_events_id'), table_name='whatsapp_events')
    op.drop_table('whatsapp_events')
    op.drop_index(op.f('ix_offer_media_id'), table_name='offer_media')
    op.drop_table('offer_media')
    # ### end Alembic commands ###