"""auto update

Revision ID: 562039a7015a
Revises: 76bc5da6536e
Create Date: 2026-07-02 19:33:55.445461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '562039a7015a'
down_revision: Union[str, Sequence[str], None] = '76bc5da6536e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('plate', sa.String(), nullable=True))
    op.alter_column('whatsapp_admin_sessions', 'state',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('whatsapp_admin_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('whatsapp_admin_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_whatsapp_admin_sessions_admin_phone'), 'whatsapp_admin_sessions', ['admin_phone'], unique=False)
    op.create_index(op.f('ix_whatsapp_admin_sessions_id'), 'whatsapp_admin_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_admin_sessions_id'), table_name='whatsapp_admin_sessions')
    op.drop_index(op.f('ix_whatsapp_admin_sessions_admin_phone'), table_name='whatsapp_admin_sessions')
    op.alter_column('whatsapp_admin_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('whatsapp_admin_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('whatsapp_admin_sessions', 'state',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'idle'::character varying"),
               existing_nullable=False)
    op.drop_column('offers', 'plate')
    # ### end Alembic commands ###