"""auto update

Revision ID: 76bc5da6536e
Revises: eb26b4e5d323
Create Date: 2026-07-02 09:06:33.442149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76bc5da6536e'
down_revision: Union[str, Sequence[str], None] = 'eb26b4e5d323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('fipe', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('fuel', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('has_manual', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('offers', sa.Column('has_spare_key', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('offers', sa.Column('target_categories', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('processed_images', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('original_images', sa.String(), nullable=True))
    op.alter_column('offers', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('offers', 'original_images')
    op.drop_column('offers', 'processed_images')
    op.drop_column('offers', 'target_categories')
    op.drop_column('offers', 'has_spare_key')
    op.drop_column('offers', 'has_manual')
    op.drop_column('offers', 'fuel')
    op.drop_column('offers', 'fipe')
    # ### end Alembic commands ###