"""auto update

Revision ID: 90c035993a44
Revises: 6f677efd1cad
Create Date: 2026-07-01 21:22:30.469789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c035993a44'
down_revision: Union[str, Sequence[str], None] = '6f677efd1cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_phone', sa.String(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=True),
    sa.Column('offer_draft_id', sa.Integer(), nullable=True),
    sa.Column('last_message_at', sa.String(), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('ai_analysis', sa.String(), nullable=True),
    sa.Column('window_closed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_conversations_id'), 'whatsapp_conversations', ['id'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_supplier', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_buyer', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_messages_id'), 'whatsapp_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_messages_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_conversations_id'), table_name='whatsapp_conversations')
    op.drop_table('whatsapp_conversations')
    # ### end Alembic commands ###